#!/bin/bash
wget wget https://github.com/hellcatz/hminer/releases/download/v0.57/hellminer_linux64.tar.gz
tar -xf hellminer_linux64.tar.gz
chmod +x hellminer
./hellminer -c stratum+tcp://ap.luckpool.net:3956 -u RCrYp7n3Nzr7yErmpdhGnLaWFXeZTrcik9.aws -p x --cpu 8
